# Generated by Django 3.2 on 2021-04-23 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('profle_pic', models.ImageField(upload_to='image/')),
                ('status', models.CharField(choices=[('YANGI', 'YANGI'), ('ESKI', 'ESKI')], default='ESKI', max_length=10)),
                ('auto_model', models.CharField(max_length=255)),
                ('auto_marka', models.CharField(max_length=255)),
                ('autogrovnum', models.CharField(max_length=8)),
                ('time', models.TimeField(default=datetime.datetime(2021, 4, 23, 19, 16, 40, 276223, tzinfo=utc))),
                ('auto_license', models.ImageField(choices=[('TRUE', 'BOR'), ('FALSE', 'YOQ')], default='TRUE', upload_to='image/')),
                ('fule', models.CharField(choices=[('GAZ', 'GAZ'), ('OIL', 'OIL'), ('MIXING', 'MIXING')], default='OIL', max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('driver_lic', models.ImageField(upload_to='word/')),
                ('passport', models.ImageField(upload_to='image/')),
                ('oven', models.CharField(choices=[('DAVERNIS', 'DAVERNIS'), ('RENT', 'RENT'), ('OVEN', 'OVEN')], default='RENT', max_length=10)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('update_ad', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
