# Generated by Django 3.2 on 2021-04-23 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxis',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 23, 19, 54, 54, 545934, tzinfo=utc)),
        ),
    ]
