# Generated by Django 3.2 on 2021-04-25 05:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_taxis_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='taxis',
            old_name='profle_pic',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='taxis',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 5, 19, 14, 289625, tzinfo=utc)),
        ),
    ]
