# Generated by Django 3.2 on 2021-04-25 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20210425_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxis',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 5, 39, 58, 773962, tzinfo=utc)),
        ),
    ]
