# Generated by Django 3.2 on 2021-04-25 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_alter_taxis_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.AlterField(
            model_name='taxis',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 5, 59, 7, 977270, tzinfo=utc)),
        ),
    ]
